name: terraform workflows

on:
  push:
  pull_request:
    branches:
      - dev
      - master
      - main
  workflow_dispatch:

jobs:
  Docs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: cumberland-cloud/workflows/.github/workflows/gh-pages.yaml@master
    with:
      TFDOCS: true
